import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  loginScreenContainer: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    padding: 24,
  },
  loginCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E8EAED',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  loginTitle: {
    fontSize: 26,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 8,
  },
  loginSubtitle: {
    fontSize: 15,
    color: '#3C4043',
    marginBottom: 14,
    lineHeight: 24,
  },
  loginButton: {
    marginTop: 4,
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    alignItems: 'center',
    paddingVertical: 13,
  },
  loginForgotButton: {
    marginTop: 10,
    alignSelf: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  loginForgotText: {
    color: '#1A73E8',
    fontSize: 13,
    fontWeight: '600',
  },
  loginInfoText: {
    marginTop: 6,
    fontSize: 12,
    color: '#2F855A',
    textAlign: 'center',
    lineHeight: 18,
  },
  loginErrorText: {
    marginTop: 6,
    fontSize: 12,
    color: '#B91C1C',
    textAlign: 'center',
    lineHeight: 18,
  },
  loginHint: {
    marginTop: 12,
    color: '#80868B',
    textAlign: 'center',
    fontSize: 13,
  },
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  screenContainer: {
    flex: 1,
    padding: 24,
  },
  formContainer: {
    padding: 24,
    paddingBottom: 40,
  },
  homeHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  homeHeaderTextWrap: {
    flex: 1,
  },
  burgerButton: {
    width: 40,
    height: 40,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  burgerButtonText: {
    color: '#3C4043',
    fontSize: 20,
    lineHeight: 22,
    fontWeight: '700',
  },
  logoutButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    paddingVertical: 10,
    paddingHorizontal: 16,
    minHeight: 40,
    justifyContent: 'center',
  },
  logoutButtonText: {
    color: '#3C4043',
    fontWeight: '600',
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: '#202124',
  },
  subtitle: {
    fontSize: 15,
    color: '#3C4043',
    marginBottom: 8,
    lineHeight: 24,
  },
  helperText: {
    color: '#80868B',
    marginBottom: 12,
    lineHeight: 24,
    fontSize: 14,
  },
  footerStatusText: {
    color: '#80868B',
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
    fontSize: 13,
    fontStyle: 'italic',
  },
  menuModalRoot: {
    flex: 1,
  },
  menuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  menuSheetWrap: {
    flex: 1,
    alignItems: 'flex-end',
    paddingTop: 76,
    paddingHorizontal: 20,
  },
  menuSheetCard: {
    width: 220,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8EAED',
    overflow: 'hidden',
  },
  menuItemButton: {
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E8EAED',
  },
  menuItemText: {
    color: '#202124',
    fontWeight: '600',
    fontSize: 14,
  },
  addStudentButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
    marginBottom: 12,
  },
  addStudentButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  studentDirectoryHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 8,
  },
  addStudentButtonInline: {
    marginBottom: 0,
    alignSelf: 'auto',
  },
  moduleCard: {
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E8EAED',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  moduleTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 4,
  },
  moduleSubtitle: {
    color: '#3C4043',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 22,
  },
  folderHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  folderTextWrap: {
    flex: 1,
  },
  folderToggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A73E8',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  folderContentCard: {
    marginTop: -4,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  searchInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EAED',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 16,
    fontSize: 15,
    color: '#3C4043',
  },
  listContent: {
    paddingBottom: 14,
  },
  classSectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8EAED',
    marginBottom: 12,
  },
  classHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  classSectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#202124',
  },
  classCountText: {
    color: '#80868B',
    fontWeight: '600',
  },
  studentItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8EAED',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  sectionCard: {
    position: 'relative',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E8EAED',
    marginBottom: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  studentName: {
    fontSize: 18,
    color: '#202124',
    fontWeight: '600',
  },
  studentClassText: {
    marginTop: 4,
    color: '#80868B',
    fontWeight: '500',
    fontSize: 14,
  },
  tapHint: {
    marginTop: 5,
    color: '#80868B',
    fontWeight: '400',
    fontSize: 13,
  },
  statusText: {
    color: '#3C4043',
    marginBottom: 10,
  },
  errorText: {
    color: '#B91C1C',
    marginBottom: 10,
    fontWeight: '600',
  },
  profileName: {
    fontSize: 29,
    color: '#202124',
    fontWeight: '600',
    marginBottom: 10,
  },
  editStudentButton: {
    alignSelf: 'flex-start',
    marginBottom: 16,
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
  },
  editStudentButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  quickLogRow: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  quickLogButton: {
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
  },
  quickLogButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  quickLogButtonSecondary: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
  },
  quickLogButtonSecondaryText: {
    color: '#3C4043',
    fontWeight: '600',
  },
  undoAbsentButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
  },
  undoAbsentButtonText: {
    color: '#3C4043',
    fontWeight: '600',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E8EAED',
    marginBottom: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '600',
    marginTop: 16,
    marginBottom: 8,
    color: '#202124',
  },
  contactButton: {
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  doctorButton: {
    backgroundColor: '#2F855A',
  },
  contactButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  allergyAlertCard: {
    backgroundColor: '#FFF3E8',
    borderColor: '#E8590C',
    borderWidth: 2,
  },
  noAllergyCard: {
    backgroundColor: '#E8F5E9',
    borderColor: '#2F855A',
  },
  allergyText: {
    color: '#7C2D12',
    fontWeight: '700',
    fontSize: 16,
  },
  vaultText: {
    fontSize: 15,
    color: '#3C4043',
    marginBottom: 7,
    lineHeight: 24,
  },
  vaultToggleButton: {
    marginTop: 10,
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    paddingVertical: 12,
    alignItems: 'center',
  },
  vaultToggleButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 24,
    borderWidth: 1,
    borderColor: '#E8EAED',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 8,
  },
  modalText: {
    fontSize: 14,
    color: '#3C4043',
    marginBottom: 12,
    lineHeight: 22,
  },
  pinInput: {
    borderWidth: 1,
    borderColor: '#E8EAED',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    marginBottom: 12,
  },
  modalButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  modalButtonSecondary: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
  },
  modalButtonSecondaryText: {
    color: '#3C4043',
    fontWeight: '600',
  },
  modalButtonPrimary: {
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
  },
  modalButtonPrimaryText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  formTitle: {
    fontSize: 24,
    color: '#202124',
    fontWeight: '600',
    marginBottom: 14,
  },
  formSectionLabel: {
    color: '#80868B',
    fontWeight: '600',
    marginBottom: 6,
    marginTop: 4,
    fontSize: 13,
  },
  formInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EAED',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 12,
    fontSize: 15,
    color: '#3C4043',
  },
  reasonInput: {
    minHeight: 48,
    textAlignVertical: 'top',
  },
  saveStudentButton: {
    marginTop: 8,
    marginBottom: 16,
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    alignItems: 'center',
    paddingVertical: 12,
    minHeight: 44,
    justifyContent: 'center',
  },
  saveStudentButtonDisabled: {
    backgroundColor: '#94A3B8',
  },
  saveStudentButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 15,
  },
  itemHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  statusBadge: {
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  statusBadgePresent: {
    backgroundColor: '#D3F9D8',
  },
  statusBadgeLate: {
    backgroundColor: '#FFF3BF',
  },
  statusBadgeAbsent: {
    backgroundColor: '#FFE3E3',
  },
  statusBadgeText: {
    fontWeight: '600',
    color: '#3C4043',
  },
  statusDot: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  statusActionButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    paddingVertical: 12,
    paddingHorizontal: 16,
    minHeight: 44,
    justifyContent: 'center',
  },
  statusActionButtonSelected: {
    backgroundColor: '#1A73E8',
    borderColor: '#1A73E8',
  },
  statusActionButtonText: {
    color: '#3C4043',
    fontWeight: '600',
  },
  chipContainer: {
    paddingBottom: 10,
    gap: 8,
  },
  chipButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginRight: 8,
    minHeight: 40,
    justifyContent: 'center',
  },
  chipButtonSelected: {
    backgroundColor: '#1A73E8',
    borderColor: '#1A73E8',
  },
  chipButtonText: {
    color: '#3C4043',
    fontWeight: '600',
  },
  selectedActionText: {
    color: '#FFFFFF',
  },
  autocompleteContainer: {
    marginBottom: 10,
  },
  searchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EAED',
    borderRadius: 6,
    paddingRight: 8,
    marginBottom: 16,
  },
  autocompleteTextInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: '#3C4043',
  },
  clearSearchButton: {
    width: 30,
    height: 30,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F3F4',
  },
  clearSearchButtonText: {
    color: '#80868B',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 20,
  },
  autocompleteResults: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EAED',
    borderRadius: 6,
    marginTop: -4,
    marginBottom: 8,
    overflow: 'hidden',
  },
  autocompleteScrollArea: {
    maxHeight: 156,
  },
  autocompleteItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E8EAED',
    minHeight: 48,
    justifyContent: 'center',
  },
  autocompleteName: {
    color: '#202124',
    fontWeight: '600',
  },
  autocompleteMeta: {
    color: '#80868B',
    marginTop: 2,
    fontSize: 12,
  },
  autocompleteEmpty: {
    color: '#80868B',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  selectedLearnerText: {
    color: '#80868B',
    fontSize: 13,
    marginTop: -2,
    marginBottom: 4,
  },
  warningCard: {
    backgroundColor: '#FFF3E8',
    borderColor: '#E8590C',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
  },
  warningText: {
    color: '#C2410C',
    fontWeight: '700',
  },
  timelineCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E8EAED',
    marginBottom: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  timelineMeta: {
    color: '#80868B',
    marginTop: 4,
    marginBottom: 8,
  },
  timelineText: {
    color: '#3C4043',
    marginBottom: 6,
    lineHeight: 20,
  },
  lockText: {
    color: '#7C2D12',
    fontWeight: '700',
    marginTop: 6,
  },
  infoBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8EAED',
    padding: 12,
    marginBottom: 16,
  },
  infoText: {
    color: '#3C4043',
    lineHeight: 22,
    fontSize: 14,
  },
  reportButton: {
    marginTop: 8,
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    alignItems: 'center',
    paddingVertical: 12,
    minHeight: 44,
    justifyContent: 'center',
  },
  complianceFolderCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8EAED',
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  complianceFolderIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 6,
    backgroundColor: '#F1F3F4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  complianceFolderIcon: {
    fontSize: 22,
  },
  complianceFolderTextWrap: {
    flex: 1,
  },
  complianceFolderLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 2,
  },
  complianceFolderDesc: {
    fontSize: 12,
    color: '#80868B',
    lineHeight: 16,
  },
  complianceFolderChevron: {
    fontSize: 13,
    color: '#1A73E8',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  complianceEmptyState: {
    alignItems: 'center',
    paddingVertical: 32,
  },
  complianceEmptyIcon: {
    fontSize: 40,
    marginBottom: 10,
  },
  complianceEmptyText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3C4043',
    marginBottom: 6,
  },
  complianceEmptyHint: {
    fontSize: 13,
    color: '#80868B',
    textAlign: 'center',
  },
  complianceDocCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8EAED',
    marginBottom: 12,
    overflow: 'hidden',
  },
  complianceDocMain: {
    flexDirection: 'row',
    padding: 14,
    alignItems: 'flex-start',
    gap: 10,
  },
  complianceDocIcon: {
    fontSize: 28,
    marginTop: 2,
  },
  complianceDocTextWrap: {
    flex: 1,
  },
  complianceDocName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 4,
  },
  complianceDocMeta: {
    fontSize: 12,
    color: '#80868B',
    marginBottom: 2,
  },
  complianceDocNotes: {
    fontSize: 12,
    color: '#3C4043',
    marginTop: 4,
    fontStyle: 'italic',
  },
  complianceDocActions: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#E8EAED',
  },
  complianceOpenBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
  },
  complianceOpenBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A73E8',
  },
  complianceDeleteBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderLeftWidth: 1,
    borderLeftColor: '#E8EAED',
  },
  complianceDeleteBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3C4043',
  },
  complianceUploadSection: {
    marginTop: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8EAED',
    padding: 20,
  },
  complianceUploadTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 10,
  },
  complianceUploadBtn: {
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    alignItems: 'center',
    paddingVertical: 12,
    minHeight: 44,
    justifyContent: 'center',
    marginTop: 4,
    marginBottom: 8,
  },
  complianceUploadBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  dateRangeLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#202124',
    marginTop: 16,
    marginBottom: 12,
  },
  datePickerRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  datePickerColumnContainer: {
    flex: 1,
  },
  datePickerLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#80868B',
    marginBottom: 6,
    textAlign: 'center',
  },
  datePickerScrollBound: {
    height: 180,
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    overflow: 'hidden',
    position: 'relative',
  },
  datePickerScroll: {
    flex: 1,
  },
  datePickerItem: {
    fontSize: 16,
    fontWeight: '500',
    color: '#80868B',
  },
  datePickerItemSelected: {
    fontSize: 18,
    fontWeight: '700',
    color: '#202124',
  },
  datePickerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: 'rgba(16, 42, 67, 0.1)',
    borderBottomColor: 'rgba(16, 42, 67, 0.1)',
    top: 65,
    height: 50,
    pointerEvents: 'none',
    zIndex: 10,
  },
  compactDateRangeContainer: {
    flexDirection: 'row',
    gap: 12,
    marginVertical: 16,
  },
  compactDateFieldWrapper: {
    flex: 1,
  },
  compactDateLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#80868B',
    marginBottom: 6,
  },
  compactDateField: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EAED',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 10,
    justifyContent: 'center',
  },
  compactDateFieldText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#3C4043',
  },
  datePickerModalRoot: {
    flex: 1,
  },
  datePickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  datePickerModalCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  datePickerModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 20,
    width: '85%',
    maxWidth: 350,
  },
  datePickerModalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 16,
    textAlign: 'center',
  },
  compactDatePickerRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  datePickerModalButtonRow: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-end',
  },
  datePickerModalCancelBtn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EAED',
  },
  datePickerModalCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3C4043',
  },
  datePickerModalConfirmBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
    backgroundColor: '#1A73E8',
  },
  datePickerModalConfirmText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  compactDatePickerColumnContainer: {
    flex: 1,
  },
  compactDatePickerLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#80868B',
    marginBottom: 6,
    textAlign: 'center',
  },
  compactDatePickerScrollBound: {
    height: 120,
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E8EAED',
    overflow: 'hidden',
    position: 'relative',
  },
  compactDatePickerScroll: {
    flex: 1,
  },
  compactDatePickerScrollContent: {
    paddingVertical: 40,
  },
  compactDatePickerItem: {
    fontSize: 13,
    fontWeight: '500',
    color: '#80868B',
  },
  compactDatePickerItemSelected: {
    fontSize: 15,
    fontWeight: '700',
    color: '#202124',
  },
  compactDatePickerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: 'rgba(16, 42, 67, 0.1)',
    borderBottomColor: 'rgba(16, 42, 67, 0.1)',
    top: 40,
    height: 40,
    pointerEvents: 'none',
    zIndex: 10,
  },
  formTextArea: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  successBanner: {
    backgroundColor: '#DCFCE7',
    borderRadius: 6,
    padding: 14,
    marginBottom: 12,
    alignItems: 'center',
  },
  successBannerText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#166534',
  },
  activityFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  activityFilterChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EAED',
  },
  activityFilterChipActive: {
    backgroundColor: '#E8F0FE',
    borderColor: '#1A73E8',
  },
  activityFilterChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3C4043',
  },
  activityFilterChipTextActive: {
    color: '#1A73E8',
  },
  activityLogButton: {
    backgroundColor: '#1A73E8',
    borderRadius: 6,
    alignItems: 'center',
    paddingVertical: 12,
    minHeight: 44,
    justifyContent: 'center',
    marginBottom: 16,
  },
  activityLogButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  activityCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8EAED',
    padding: 20,
    marginBottom: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  activityCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  activityCardHeaderText: {
    flex: 1,
    marginRight: 8,
  },
  activityCardName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#202124',
    marginBottom: 2,
  },
  activityCardMeta: {
    fontSize: 13,
    color: '#80868B',
  },
  activityCardBadge: {
    backgroundColor: '#E8F0FE',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  activityCardBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1A73E8',
  },
  activityCardDetail: {
    fontSize: 14,
    color: '#3C4043',
    marginBottom: 4,
    lineHeight: 22,
  },
  activityCardBody: {
    fontSize: 14,
    color: '#3C4043',
    lineHeight: 22,
    marginTop: 4,
    marginBottom: 4,
  },
  activityCardFooter: {
    fontSize: 12,
    color: '#80868B',
    marginTop: 6,
  },
  activityDeleteButton: {
    marginTop: 10,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 6,
    backgroundColor: '#FFF5F5',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  activityDeleteButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#C92A2A',
  },
  activityFilePickButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EAED',
    borderRadius: 6,
    alignItems: 'center',
    paddingVertical: 12,
    minHeight: 44,
    justifyContent: 'center',
    marginBottom: 6,
  },
  activityFilePickButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1A73E8',
  },
  activityRemoveFile: {
    fontSize: 13,
    color: '#C92A2A',
    textAlign: 'center',
    marginBottom: 12,
  },
  activityCardActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 10,
  },
  activityEditButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    backgroundColor: '#E8F0FE',
    borderWidth: 1,
    borderColor: '#1A73E8',
    minHeight: 40,
    justifyContent: 'center',
  },
  activityEditButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1A73E8',
  },
  activityDetailRow: {
    marginBottom: 10,
  },
  activityDetailLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#80868B',
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  activityDetailValue: {
    fontSize: 14,
    color: '#3C4043',
    lineHeight: 22,
  },
});

export default styles;
